server:
  port: 10333

spring:
  datasource-data:
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://s4.java21.net:13306/project_be11_team2_dev?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be11_team2
    password: F@R_UmfIzCl0uW)8
    dbcp2:
      initial-size: 100
      max-total: 200
      min-idle: 100
      max-idle: 200

  data:
    redis:
      host: ${REDIS_HOST:s4.java21.net}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:*N2vya7H@muDTwdNMR!}
      database: ${REDIS_DATABASE:321}

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true

  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 4

  rabbitmq:
    host: ${RABBITMQ_HOST:s4.java21.net}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:nhnacademy123!}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:byeol23}

  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://ollama.java21.net}
      embedding:
        options:
          model: bge-m3

jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiNJoRcPJmLQ7Ii+hv78JNhtSgo7w7u8TS3PsftAMKBvkqpeAInmnpra1usEPhXTVWOyLLxL6yJAymKY8lzDf3I74T0F4GJiomkjjOdIT5TEAc5X3um+IuHxu7Qapr0BuKwBvT4FCBJ9jzPOCq8xkh2q/AWGfOTlPLjBmAVnp2NbbV4aI5cQR6D9a/extPX6hhAtq/NZqE665L/SVIXqPabu2Owpvn90O6HtNXzg6ytk7Rj4FBx6YLtqHy0QAf8/o/Zc1nr+ZHwSsDQ+am6Sp2ZmUl03ScerF7EMtfZyzUqY46RFNgUkhB7iJb2hZ3xYGtR9SUI+PDvt2Kz6AETewhQIDAQAB

eureka:
  client:
    healthcheck:
      enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10338/dashboard/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}

book:
  outbox:
    exchange: byeol23.dev.book.outbox.exchange
    queue: byeol23.dev.book.outbox.queue
    routing-key: byeol23.dev.book.outbox.key

  reindex:
    exchange: byeol23.dev.book.reindex.status.exchange
    queue: byeol23.dev.book.reindex.status.queue
    routing-key: byeol23.dev.book.reindex.status.key

  embedding:
    exchange: byeol23.dev.book.embedding.exchange
    queue: byeol23.dev.book.embedding.queue
    routing-key: byeol23.dev.book.embedding.key

coupon:
  issue:
    exchange: byeol23.dev.coupon.issue.exchange

  bulk:
    queue: byeol23.dev.coupon.issue.bulk.queue
    routing-key: byeol23.dev.coupon.issue.bulk.key

  birthday:
    queue: byeol23.dev.coupon.issue.birthday.queue
    routing-key: byeol23.dev.coupon.issue.birthday.key

    policy-id: 11
    coupon-name-template: "[생일 축하] {MONTH}월 혜택 쿠폰"
    validity-days: 30
  welcome:
    policy-id: 12
    coupon-name-template: "[Welcome] 신규회원 쿠폰"
    validity-days: 30



management:
  health:
    redis:
      enabled: false

    elasticsearch:
      enabled: false

tossPayment:
  secretKey: test_sk_26DlbXAaV0wkDZNmNMJ43qY50Q9R
