server:
  port: 10333

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource

    url: jdbc:mysql://s4.java21.net:13306/project_be11_team2_dev?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be11_team2
    password: F@R_UmfIzCl0uW)8
    dbcp2:
      initial-size: 5
      max-total: 50

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 321

  elasticsearch:
    uris: http://${ES_HOST:s4.java21.net}:${ES_PORT:9200}
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:nhnacademy123!}

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true

  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 4

  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      embedding:
        options:
          model: bge-m3

jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiNJoRcPJmLQ7Ii+hv78JNhtSgo7w7u8TS3PsftAMKBvkqpeAInmnpra1usEPhXTVWOyLLxL6yJAymKY8lzDf3I74T0F4GJiomkjjOdIT5TEAc5X3um+IuHxu7Qapr0BuKwBvT4FCBJ9jzPOCq8xkh2q/AWGfOTlPLjBmAVnp2NbbV4aI5cQR6D9a/extPX6hhAtq/NZqE665L/SVIXqPabu2Owpvn90O6HtNXzg6ytk7Rj4FBx6YLtqHy0QAf8/o/Zc1nr+ZHwSsDQ+am6Sp2ZmUl03ScerF7EMtfZyzUqY46RFNgUkhB7iJb2hZ3xYGtR9SUI+PDvt2Kz6AETewhQIDAQAB

eureka:
  client:
    healthcheck:
      enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10338/dashboard/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}