server:
  port: 10332
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: byeol23-backend
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: validate

  profiles:
    active: dev

logging:
  level:
    root: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
    org.apache.commons.dbcp2: DEBUG

tossPayment:
  secretKey: test_sk_26DlbXAaV0wkDZNmNMJ43qY50Q9R

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10338/dashboard/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiNJoRcPJmLQ7Ii+hv78J
    NhtSgo7w7u8TS3PsftAMKBvkqpeAInmnpra1usEPhXTVWOyLLxL6yJAymKY8lzDf
    3I74T0F4GJiomkjjOdIT5TEAc5X3um+IuHxu7Qapr0BuKwBvT4FCBJ9jzPOCq8xk
    h2q/AWGfOTlPLjBmAVnp2NbbV4aI5cQR6D9a/extPX6hhAtq/NZqE665L/SVIXqP
    abu2Owpvn90O6HtNXzg6ytk7Rj4FBx6YLtqHy0QAf8/o/Zc1nr+ZHwSsDQ+am6Sp
    2ZmUl03ScerF7EMtfZyzUqY46RFNgUkhB7iJb2hZ3xYGtR9SUI+PDvt2Kz6AETew
    hQIDAQAB
    -----END PUBLIC KEY-----

