name: Java CI with Maven (Backend)

on:
  push:
    branches: [ "main" ]

env:
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Analyze Backend with SonarQube
        run: mvn verify sonar:sonar -Dsonar.projectKey=byeol23-back -Dsonar.host.url=${{ env.SONAR_HOST_URL }} -Dsonar.token=${{ env.SONAR_TOKEN }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: upload file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "target/*.jar"
          target: "~/"
          rm: false

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            # 1. 서비스에 필요한 .env 파일을 서버에 생성 (덮어쓰기)
            echo "PROD_DB_URL=${{ secrets.PROD_DB_URL }}" > ~/.env
            echo "PROD_DB_USERNAME=${{ secrets.PROD_DB_USERNAME }}" >> ~/.env
            echo "PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> ~/.env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> ~/.env
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> ~/.env
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> ~/.env
            echo "REDIS_DATABASE=${{ secrets.REDIS_DATABASE }}" >> ~/.env
            echo "JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }}" >> ~/.env
            
            # 2. startup.sh 스크립트에 실행 권한 부여
            chmod +x ~/startup.sh
            
            # 3. .env 파일을 읽어서 실행할 startup.sh 호출
            bash ~/startup.sh backend